baseurl = "https://omsriver.github.io/thoughtshelf/"
languageCode = "en-us"
title = "Om's River"


[Params]
	Author = "Mitul Shah"
	disqusShortname = "omsriver-github-io"
	googleAnalytics = "UA-84678477-1"
